-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 20:20:06 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema stickers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stickers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stickers` DEFAULT CHARACTER SET utf8 ;
USE `stickers` ;

-- -----------------------------------------------------
-- Table `stickers`.`accaunts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stickers`.`accaunts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `confirm` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stickers`.`boards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stickers`.`boards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `creator` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `creator_idx` (`creator` ASC),
  CONSTRAINT `boards creator`
    FOREIGN KEY (`creator`)
    REFERENCES `stickers`.`accaunts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stickers`.`stickers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stickers`.`stickers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  `board` INT NOT NULL,
  `creator` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `board_idx` (`board` ASC),
  INDEX `creator_idx` (`creator` ASC),
  CONSTRAINT `board`
    FOREIGN KEY (`board`)
    REFERENCES `stickers`.`boards` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `stickers creator`
    FOREIGN KEY (`creator`)
    REFERENCES `stickers`.`accaunts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stickers`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stickers`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `boards` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_boards1_idx` (`boards` ASC),
  CONSTRAINT `fk_groups_boards1`
    FOREIGN KEY (`boards`)
    REFERENCES `stickers`.`boards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stickers`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stickers`.`operations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stickers`.`operations_for_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stickers`.`operations_for_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group` INT NULL,
  `operation` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_idx` (`group` ASC),
  INDEX `fk_operaion_idx` (`operation` ASC),
  UNIQUE INDEX `unique` (`group` ASC, `operation` ASC),
  CONSTRAINT `fk_group`
    FOREIGN KEY (`group`)
    REFERENCES `stickers`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operaion`
    FOREIGN KEY (`operation`)
    REFERENCES `stickers`.`operations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
